[package]
name = "cirklon2-desktop-app"
description = "Instrument definitions for the Sequentix Cirklon"
version.workspace = true
edition.workspace = true

[lib]
name = "cirklon2_desktop_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
cirklon-core = { path = "../core" }
